<?php
declare(strict_types=1);

namespace Gedankenfolger\GedankenfolgerViewhelper\ViewHelpers\Composer;

use Composer\InstalledVersions;
use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;

/**
 * <gf:composer.packageInfo name="vendor/package" key="prettyVersion" />
 * <gf:composer.packageInfo name="vendor/package" /> <!-- returns array -->
 *
 * This ViewHelper exposes package metadata as reported by Composer\InstalledVersions.
 * It does NOT parse composer.json or ext_emconf.php and therefore only returns data
 * available from Composer itself.
 *
 * Security:
 *  - Server paths can be sensitive. They are NOT exposed by default.
 *    Set exposeInstallPath="1" to include the absolute install path.
 *
 * Performance:
 *  - Uses InstalledVersions directly (in-memory map generated by Composer),
 *    which is fast and does not hit the filesystem.
 *
 * @api
 * @since 1.0.0
 */
final class PackageInfoViewHelper extends AbstractViewHelper
{
    /**
     * Registers arguments.
     *
     * name:
     *  - Either a Composer package name ("vendor/package")
     *  - Or an extension key ("my_ext") if heuristicResolve=true. The heuristic
     *    will try to find a package ending with "/{extKey}".
     *
     * key:
     *  - Optional field selector. When omitted, the full associative array is returned.
     *    Allowed keys: packageName, isInstalled, version, prettyVersion, reference, installPath
     *
     * jsonEncode:
     *  - If true, the result is JSON-encoded (useful for arrays in Fluid).
     *
     * heuristicResolve:
     *  - If true (default), an argument without slash is treated as extension key and
     *    resolved heuristically to a package (best effort).
     *
     * exposeInstallPath:
     *  - If true, include the absolute install path. Default is false for security reasons.
     */
    public function initializeArguments(): void
    {
        $this->registerArgument('name', 'string', 'Composer package name ("vendor/package") or ext key if heuristicResolve=1.', true);
        $this->registerArgument('key', 'string', 'Optional key to return: packageName|isInstalled|version|prettyVersion|reference|installPath.', false, '');
        $this->registerArgument('jsonEncode', 'bool', 'Return JSON-encoded result (useful for arrays).', false, false);
        $this->registerArgument('heuristicResolve', 'bool', 'Resolve ext key to package by suffix match if no slash is present.', false, true);
        $this->registerArgument('exposeInstallPath', 'bool', 'Include absolute install path (can be sensitive).', false, false);
    }

    /**
     * Executes the ViewHelper.
     *
     * @return mixed Scalar|string|array|null
     */
    public function render()
    {
        $name = trim((string)$this->arguments['name']);
        $key = (string)$this->arguments['key'];
        $json = (bool)$this->arguments['jsonEncode'];
        $allowHeuristic = (bool)$this->arguments['heuristicResolve'];
        $exposeInstallPath = (bool)$this->arguments['exposeInstallPath'];

        if ($name === '' || !class_exists(InstalledVersions::class)) {
            return '';
        }

        // Resolve final package name
        $packageName = null;
        if (str_contains($name, '/')) {
            $packageName = $name;
        } elseif ($allowHeuristic) {
            $packageName = $this->resolvePackageByExtKeyHeuristic($name);
        }

        if ($packageName === null) {
            return '';
        }

        $info = $this->buildInfoFromInstalledVersions($packageName, $exposeInstallPath);

        if ($info === null) {
            return '';
        }

        $result = $key !== '' ? ($info[$key] ?? null) : $info;

        if ($json) {
            return json_encode($result, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR | JSON_PRESERVE_ZERO_FRACTION);
        }

        return $result;
    }

    /**
     * Creates a normalized info array from Composer\InstalledVersions.
     *
     * @param string $packageName Composer package name.
     * @param bool   $exposeInstallPath If true, include the absolute install path.
     * @return array<string,mixed>|null
     */
    private function buildInfoFromInstalledVersions(string $packageName, bool $exposeInstallPath): ?array
    {
        // isInstalled() is the fast path; avoids exceptions on lookups.
        $isInstalled = InstalledVersions::isInstalled($packageName);

        // Always return a consistent shape, even if not installed.
        $result = [
            'packageName'   => $packageName,
            'isInstalled'   => $isInstalled,
            'version'       => null,
            'prettyVersion' => null,
            'reference'     => null,
            // installPath is added later only if requested
        ];

        if (!$isInstalled) {
            return $result;
        }

        // These calls are O(1) lookups against Composer's static data.
        $version = null;
        $prettyVersion = null;
        $reference = null;

        try {
            $version = InstalledVersions::getVersion($packageName);
        } catch (\Throwable) {
            // ignore
        }

        try {
            $prettyVersion = InstalledVersions::getPrettyVersion($packageName);
        } catch (\Throwable) {
            // ignore
        }

        // getReference() exists on newer Composer versions; feature-detect defensively.
        if (method_exists(InstalledVersions::class, 'getReference')) {
            try {
                $reference = InstalledVersions::getReference($packageName);
            } catch (\Throwable) {
                // ignore
            }
        }

        $result['version'] = $version;
        $result['prettyVersion'] = $prettyVersion ?? $version;
        $result['reference'] = $reference;

        if ($exposeInstallPath) {
            try {
                $installPath = InstalledVersions::getInstallPath($packageName) ?: null;
                $result['installPath'] = $installPath;
            } catch (\Throwable) {
                // ignore
            }
        }

        return $result;
    }

    /**
     * Best-effort resolution for extension keys: find a package whose name ends with "/{extKey}".
     * This is intentionally simple and fast; it avoids filesystem scans.
     *
     * @param string $extKey Extension key (e.g., "my_ext").
     * @return string|null Composer package name or null if none matched.
     */
    private function resolvePackageByExtKeyHeuristic(string $extKey): ?string
    {
        try {
            foreach (InstalledVersions::getInstalledPackages() as $pkg) {
                if (str_ends_with($pkg, '/' . $extKey)) {
                    return $pkg;
                }
            }
        } catch (\Throwable) {
            // ignore
        }
        return null;
    }
}
